// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CurrencyMaskController from "./currency_mask_controller.js"
application.register("currency-mask", CurrencyMaskController)

import RidingsOnboardingController from "./ridings_onboarding_controller.js"
application.register("ridings-onboarding", RidingsOnboardingController)

import WelcomeController from "./welcome_controller.js"
application.register("welcome", WelcomeController)

import CheckboxSelectAll from "stimulus-checkbox-select-all"
application.register("checkbox-select-all", CheckboxSelectAll)

import Modal from "./modal_controller.js"
application.register('modal', Modal)

import Tooltip from "./tooltip_controller.js"
application.register('tooltip', Tooltip)